services:
  app-dm-energy-consumption:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    command: bash -c "poetry run python src/main.py"
    container_name: dm-energy-consumption
    volumes:
      - .:/dm-energy-consumption
    env_file:
      - /.env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-dm-energy-consumption/${POSTGRES_DB}
    ports:
      - "8300:8300"
    depends_on:
      db-dm-energy-consumption:
        condition: service_healthy

  db-dm-energy-consumption:
    container_name: postgresql_db
    image: postgres:15
    volumes:
      - ./data/db-dm-energy-consumption:/var/lib/postgresql/data
    env_file:
      - /.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      timeout: 30s
      retries: 6
