version: '3.9'

services:
  app-dm-energy-consumption:
    networks:
      - dm-energy-consumption
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    command: bash -c "poetry run python src/main.py"
    container_name: dm-energy-consumption
    ports:
      - "8300:8300"

  db-dm-energy-consumption:
    container_name: db-energy-consumption
    image: postgres:15
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      timeout: 30s
      retries: 6

networks:
  dm-energy-consumption:
